---
galaxy_info:
  author: Juan Orti
  description: fail2ban for Fedora
  license: GPLv3
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
      - 7
  - name: Fedora
    versions:
      - all
  categories:
  - system
  - networking
dependencies: []
