---
fail2ban_packages:
  - fail2ban
  - ipset
fail2ban_configdir: /etc/fail2ban
fail2ban_loglevel: INFO
fail2ban_logtarget: SYSLOG
fail2ban_backend: systemd
fail2ban_banaction: firewallcmd-ipset
fail2ban_bantime: 3600
fail2ban_jails:
  - sshd
